SKILL_CATALOG = [
    {
        "name": "nl2sql",
        "title": "NL to SQL",
        "version": "1.0.0",
        "status": "active",
        "owner": "AI Platform",
        "description": "Converts governed business questions into SQL using semantic context.",
        "scope": ["chat", "semantic-context", "sql-generation"],
        "guardrails": [
            "Read-only SQL only",
            "Use approved semantic mappings",
            "No invented metrics",
        ],
    },
    {
        "name": "sql-validator",
        "title": "SQL Validator",
        "version": "1.0.0",
        "status": "active",
        "owner": "AI Platform",
        "description": "Validates generated SQL for safety and basic correctness.",
        "scope": ["sql-validation", "guardrails"],
        "guardrails": [
            "Block DDL/DML",
            "Auto-add LIMIT",
            "Reject unsafe patterns",
        ],
    },
    {
        "name": "query-router",
        "title": "Query Router",
        "version": "1.0.0",
        "status": "active",
        "owner": "Data Platform",
        "description": "Chooses the right execution engine based on semantic context and workload shape.",
        "scope": ["engine-routing", "execution-abstraction"],
        "guardrails": [
            "Prefer governed engine mapping",
            "Fallback safely",
        ],
    },
    {
        "name": "chart-recommender",
        "title": "Chart Recommender",
        "version": "1.0.0",
        "status": "active",
        "owner": "Frontend + AI",
        "description": "Infers appropriate charts from query result shape.",
        "scope": ["chart-recommendation", "visualization"],
        "guardrails": [
            "Fallback to table if needed",
            "Use shape-based rules",
        ],
    },
    {
        "name": "insight-generator",
        "title": "Insight Generator",
        "version": "1.0.0",
        "status": "beta",
        "owner": "AI Platform",
        "description": "Generates structured business insights from grounded results and semantic context.",
        "scope": ["insights", "follow-ups", "assumptions"],
        "guardrails": [
            "No hidden chain-of-thought",
            "Ground outputs in context",
        ],
    },
]
