#!/usr/bin/env python3
"""
Load synthetic CC data from CSV files into StarRocks.

Expects CSV files in ./raw/ directory generated by generate_synthetic_data.py
"""

import os
import mysql.connector
import csv
from decimal import Decimal
from datetime import datetime, date

def connect_starrocks():
    """Connect to StarRocks"""
    conn = mysql.connector.connect(
        host='localhost',
        port=9030,
        database='cc_analytics',
        user='root',
        password=''
    )
    return conn

def load_csv_into_table(conn, cursor, table_name, csv_file):
    """Load CSV file into StarRocks table"""
    if not os.path.exists(csv_file):
        print(f"Warning: {csv_file} not found, skipping...")
        return 0

    row_count = 0
    try:
        with open(csv_file, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            rows = list(reader)

            if not rows:
                print(f"No data in {csv_file}")
                return 0

            # Build insert statement
            columns = list(rows[0].keys())
            placeholders = ','.join(['%s'] * len(columns))
            insert_sql = f"INSERT INTO {table_name} ({','.join(columns)}) VALUES ({placeholders})"

            # Prepare data
            for row in rows:
                values = []
                for col in columns:
                    val = row[col]

                    # Handle datetime/date conversions
                    if val == 'None' or val == '':
                        val = None
                    elif col in ['transaction_date', 'alert_date', 'created_at', 'dispute_date']:
                        try:
                            val = datetime.strptime(val, '%Y-%m-%d %H:%M:%S') if val else None
                        except:
                            try:
                                val = datetime.strptime(val, '%Y-%m-%d') if val else None
                            except:
                                val = None
                    elif col in ['statement_date', 'open_date', 'close_date', 'issued_date',
                                 'expiration_date', 'payment_due_date', 'date_of_birth',
                                 'event_date', 'payment_date']:
                        if val:
                            try:
                                val = datetime.strptime(val, '%Y-%m-%d').date()
                            except:
                                val = None
                    elif col in ['credit_score', 'points_earned', 'points_redeemed', 'cycle_day',
                                 'ssn_last4']:
                        val = int(val) if val else 0
                    elif col in ['dispute_flag', 'autopay_flag', 'revolving_flag', 'confirmed_fraud']:
                        if val is not None and str(val).lower() in ['true', '1', 'yes']:
                            val = 1
                        else:
                            val = 0
                    elif col in ['apr', 'fraud_score', 'utilization_rate']:
                        val = Decimal(val) if val else Decimal('0')
                    elif col in ['credit_limit', 'amount', 'ending_balance', 'minimum_due',
                                 'interchange_fee']:
                        val = Decimal(val) if val else Decimal('0')

                    values.append(val)

                try:
                    cursor.execute(insert_sql, values)
                    row_count += 1
                except Exception as e:
                    print(f"Error inserting row: {e}")
                    continue

        conn.commit()
        print(f"Loaded {row_count} rows into {table_name}")
    except Exception as e:
        print(f"Error loading {csv_file}: {e}")
        conn.rollback()

    return row_count

def main():
    print("Loading synthetic CC data into StarRocks...")

    try:
        conn = connect_starrocks()
        cursor = conn.cursor()

        # Execute DDL to create database and tables first
        ddl_file = '/home/acs1980/workspace/dataprismai/data/ddl/starrocks/00_raw_cc_tables.sql'
        if os.path.exists(ddl_file):
            print("Creating StarRocks tables...")
            with open(ddl_file, 'r') as f:
                sql_statements = f.read().split(';')
                for statement in sql_statements:
                    if statement.strip():
                        try:
                            cursor.execute(statement)
                        except Exception as e:
                            print(f"Warning: {e}")
            conn.commit()

        # Load CSV files
        base_dir = '/home/acs1980/workspace/dataprismai/data/synthetic/raw'

        table_mappings = [
            ('cc_analytics.raw_customers', os.path.join(base_dir, 'customers.csv')),
            ('cc_analytics.raw_merchants', os.path.join(base_dir, 'merchants.csv')),
            ('cc_analytics.raw_card_accounts', os.path.join(base_dir, 'card_accounts.csv')),
            ('cc_analytics.raw_cards', os.path.join(base_dir, 'cards.csv')),
            ('cc_analytics.raw_transactions', os.path.join(base_dir, 'transactions.csv')),
            ('cc_analytics.raw_statements', os.path.join(base_dir, 'statements.csv')),
            ('cc_analytics.raw_payments', os.path.join(base_dir, 'payments.csv')),
            ('cc_analytics.raw_disputes', os.path.join(base_dir, 'disputes.csv')),
            ('cc_analytics.raw_fraud_alerts', os.path.join(base_dir, 'fraud_alerts.csv')),
        ]

        total_rows = 0
        for table, csv_file in table_mappings:
            rows = load_csv_into_table(conn, cursor, table, csv_file)
            total_rows += rows

        print(f"\nTotal rows loaded: {total_rows}")
        print("StarRocks data load complete!")

        cursor.close()
        conn.close()

    except Exception as e:
        print(f"Error: {e}")
        exit(1)

if __name__ == '__main__':
    main()
