sys_log_level = INFO
http_port = 8030
rpc_port = 9020
query_port = 9030
edit_log_port = 9010
mysql_service_nio_enabled = true
charset = UTF-8
priority_networks = 172.18.0.0/16
start_with_incomplete_meta = true
