from __future__ import annotations

from app.core.config import settings
from app.services.vanna_training_context import build_training_context


class VannaService:
    def __init__(self) -> None:
        self.enabled = settings.use_vanna
        self._client = None

        if self.enabled:
            try:
                from vanna.base import VannaBase

                class LocalVanna(VannaBase):
                    def __init__(self):
                        super().__init__()

                    def submit_prompt(self, prompt, **kwargs):
                        raise NotImplementedError(
                            "Custom prompt submission is not implemented in this starter."
                        )

                self._client = LocalVanna()
            except Exception:
                self._client = None
                self.enabled = False

    def is_ready(self) -> bool:
        return self.enabled and self._client is not None

    def generate_sql(self, question: str, semantic_context: dict) -> dict:
        if not self.is_ready():
            raise RuntimeError("Vanna is not ready")

        training = build_training_context(semantic_context)

        ddl = training["ddl"]
        documentation = training["documentation"]
        examples = training["examples"]

        try:
            # Training calls are kept lightweight for now.
            self._client.train(ddl=ddl)
            self._client.train(documentation=documentation)

            for example in examples:
                self._client.train(
                    question=example["question"],
                    sql=example["sql"],
                )

            sql = self._client.generate_sql(question=question)

            return {
                "sql": sql.strip(),
                "explanation": "SQL generated by Vanna using semantic training context.",
                "assumptions": [
                    "Vanna used semantic_model_table as the base table.",
                    "Lightweight training context was applied at request time.",
                ],
            }
        except Exception as exc:
            raise RuntimeError(f"Vanna SQL generation failed: {exc}") from exc


vanna_service = VannaService()
