"""initial

Revision ID: 5adddc8afc34
Revises:
Create Date: 2026-04-04 01:35:42.182055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5adddc8afc34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('graph_state_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_thread_id', 'agent_runs', ['thread_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_msg_conversation_id', 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_product',
    sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('grain', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('engine', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('refresh_policy', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sla_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('product_name', name=op.f('data_product_pkey'))
    )
    op.create_table('semantic_dimension',
    sa.Column('dimension_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dimension_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('definition', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('allowed_values_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('dimension_id', name=op.f('semantic_dimension_pkey')),
    sa.UniqueConstraint('dimension_name', name=op.f('semantic_dimension_dimension_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_semantic_dimension_name'), 'semantic_dimension', ['dimension_name'], unique=False)
    op.create_table('semantic_metric',
    sa.Column('metric_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('metric_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('definition', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('grain', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('default_engine', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sql_expression', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('metric_id', name=op.f('semantic_metric_pkey')),
    sa.UniqueConstraint('metric_name', name=op.f('semantic_metric_metric_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_semantic_metric_name'), 'semantic_metric', ['metric_name'], unique=False)
    op.create_table('semantic_join_path',
    sa.Column('join_path_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('left_entity', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('right_entity', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('join_sql', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('join_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('approved_flag', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('join_path_id', name=op.f('semantic_join_path_pkey'))
    )
    op.create_table('lineage_edge',
    sa.Column('source_object', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('target_object', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('source_object', 'target_object', 'relation_type', name=op.f('lineage_edge_pkey'))
    )
    op.create_index(op.f('idx_lineage_target'), 'lineage_edge', ['target_object'], unique=False)
    op.create_index(op.f('idx_lineage_source'), 'lineage_edge', ['source_object'], unique=False)
    op.create_table('semantic_synonym',
    sa.Column('synonym', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('synonym', name=op.f('semantic_synonym_pkey'))
    )
    op.create_index(op.f('idx_semantic_synonym_target'), 'semantic_synonym', ['target_name'], unique=False)
    op.create_table('semantic_entity',
    sa.Column('entity_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('natural_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('surrogate_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('semantic_entity_pkey')),
    sa.UniqueConstraint('entity_name', name=op.f('semantic_entity_entity_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_semantic_entity_name'), 'semantic_entity', ['entity_name'], unique=False)
    op.drop_table('reports')
    op.drop_table('conversations')
    op.drop_index('ix_msg_conversation_id', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('ix_agent_runs_thread_id', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
